"""Report generation: branded PDF (fpdf2) with an HTML print fallback."""

from __future__ import annotations

import html
import io
from datetime import UTC, datetime
from typing import Any

from app.core.logging_config import get_logger
from app.ml.document_analyzer import DISCLAIMER

logger = get_logger(__name__)

try:
    from fpdf import FPDF

    FPDF_AVAILABLE = True
except Exception:  # pragma: no cover
    FPDF_AVAILABLE = False

BRAND = "FraudShield AI"
TAGLINE = "AI-Powered Digital Fraud Detection & Risk Analysis"

# Brand palette (RGB).
_INK = (17, 24, 39)
_MUTED = (100, 116, 139)
_LINE = (226, 232, 240)
_ACCENT = (14, 165, 233)
_LEVEL_COLOURS: dict[str, tuple[int, int, int]] = {
    "LOW": (16, 185, 129),
    "MEDIUM": (245, 158, 11),
    "HIGH": (249, 115, 22),
    "CRITICAL": (239, 68, 68),
}

_SEVERITY_LABEL = {
    "critical": "CRITICAL",
    "high": "HIGH",
    "medium": "MEDIUM",
    "low": "LOW",
    "info": "INFO",
}


def _ascii(text: Any) -> str:
    """fpdf2's core fonts are Latin-1; drop anything outside it."""
    value = "" if text is None else str(text)
    replacements = {
        "–": "-",
        "—": "-",
        "‘": "'",
        "’": "'",
        "“": '"',
        "”": '"',
        "…": "...",
        "₹": "Rs.",
        "→": "->",
        " ": " ",
    }
    for needle, replacement in replacements.items():
        value = value.replace(needle, replacement)
    return value.encode("latin-1", "replace").decode("latin-1")


def _format_timestamp(value: Any) -> str:
    if isinstance(value, datetime):
        moment = value if value.tzinfo else value.replace(tzinfo=UTC)
        return moment.strftime("%d %b %Y, %H:%M UTC")
    return str(value or "-")


class _ReportPDF(FPDF if FPDF_AVAILABLE else object):  # type: ignore[misc]
    """A4 report with a branded header and a numbered footer."""

    def header(self) -> None:  # pragma: no cover - visual
        self.set_fill_color(*_INK)
        self.rect(0, 0, 210, 24, style="F")
        self.set_xy(12, 6)
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(255, 255, 255)
        self.cell(0, 7, _ascii(BRAND), new_x="LMARGIN", new_y="NEXT")
        self.set_x(12)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(170, 190, 215)
        self.cell(0, 5, _ascii(TAGLINE))
        self.set_xy(150, 9)
        self.set_font("Helvetica", "", 8)
        self.cell(48, 5, _ascii("FRAUD ANALYSIS REPORT"), align="R")
        self.set_y(32)
        self.set_text_color(*_INK)

    def footer(self) -> None:  # pragma: no cover - visual
        self.set_y(-16)
        self.set_draw_color(*_LINE)
        self.line(12, self.get_y(), 198, self.get_y())
        self.set_y(-13)
        self.set_font("Helvetica", "", 7.5)
        self.set_text_color(*_MUTED)
        self.cell(
            0,
            5,
            _ascii(
                "Automated risk assessment - not forensic verification. "
                f"Generated by {BRAND}."
            ),
        )
        self.cell(0, 5, _ascii(f"Page {self.page_no()}/{{nb}}"), align="R")


def _section(pdf: "_ReportPDF", title: str) -> None:
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 10.5)
    pdf.set_text_color(*_INK)
    pdf.cell(0, 6, _ascii(title.upper()), new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(*_ACCENT)
    pdf.set_line_width(0.6)
    pdf.line(12, pdf.get_y(), 42, pdf.get_y())
    pdf.set_line_width(0.2)
    pdf.ln(2.5)


def _key_value_rows(pdf: "_ReportPDF", rows: list[tuple[str, str]]) -> None:
    for label, value in rows:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_MUTED)
        pdf.cell(42, 6, _ascii(label))
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_INK)
        pdf.multi_cell(144, 6, _ascii(value) or "-", new_x="LMARGIN", new_y="NEXT")


def _risk_banner(pdf: "_ReportPDF", score: float, level: str, prediction: str) -> None:
    colour = _LEVEL_COLOURS.get(level.upper(), _MUTED)
    top = pdf.get_y()

    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(*_LINE)
    pdf.rect(12, top, 186, 26, style="DF")
    pdf.set_fill_color(*colour)
    pdf.rect(12, top, 3, 26, style="F")

    pdf.set_xy(20, top + 4)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*colour)
    pdf.cell(34, 10, _ascii(f"{score:.0f}"))
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*_MUTED)
    pdf.set_xy(20, top + 15)
    pdf.cell(34, 5, _ascii("/ 100 RISK SCORE"))

    pdf.set_xy(66, top + 5)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*colour)
    pdf.cell(60, 7, _ascii(f"{level.upper()} RISK"))
    pdf.set_xy(66, top + 13)
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(*_INK)
    pdf.cell(120, 6, _ascii(f"Classification: {prediction}"))

    # Score meter.
    bar_x, bar_y, bar_w = 132, top + 17, 58
    pdf.set_fill_color(226, 232, 240)
    pdf.rect(bar_x, bar_y, bar_w, 3.2, style="F")
    pdf.set_fill_color(*colour)
    pdf.rect(bar_x, bar_y, max(1.0, bar_w * min(score, 100) / 100), 3.2, style="F")
    pdf.set_xy(bar_x, bar_y - 6)
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_text_color(*_MUTED)
    pdf.cell(bar_w, 4, _ascii("RISK METER"), align="R")

    pdf.set_y(top + 30)
    pdf.set_text_color(*_INK)


def _paragraph(pdf: "_ReportPDF", text: str) -> None:
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(*_INK)
    pdf.multi_cell(186, 5.2, _ascii(text) or "-", new_x="LMARGIN", new_y="NEXT")


def _indicator_table(pdf: "_ReportPDF", indicators: list[dict[str, Any]]) -> None:
    if not indicators:
        _paragraph(pdf, "No suspicious indicators were detected for this scan.")
        return

    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*_INK)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(22, 6.5, _ascii(" SEVERITY"), fill=True)
    pdf.cell(14, 6.5, _ascii("WEIGHT"), fill=True, align="C")
    pdf.cell(150, 6.5, _ascii(" INDICATOR / EXPLANATION"), fill=True, new_x="LMARGIN", new_y="NEXT")

    for index, indicator in enumerate(indicators[:14]):
        severity = str(indicator.get("severity", "low")).lower()
        colour = _LEVEL_COLOURS.get(
            {"critical": "CRITICAL", "high": "HIGH", "medium": "MEDIUM"}.get(severity, "LOW"),
            _MUTED,
        )
        if pdf.get_y() > 250:
            pdf.add_page()

        row_top = pdf.get_y()
        if index % 2 == 0:
            pdf.set_fill_color(249, 250, 251)
            pdf.rect(12, row_top, 186, 5.6, style="F")

        pdf.set_xy(12, row_top)
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(*colour)
        pdf.cell(22, 5.6, _ascii(" " + _SEVERITY_LABEL.get(severity, severity.upper())))
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*_MUTED)
        pdf.cell(14, 5.6, _ascii(f"{float(indicator.get('weight', 0) or 0):.0f}"), align="C")
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_text_color(*_INK)
        pdf.multi_cell(
            150, 5.6, _ascii(str(indicator.get("label", "-"))), new_x="LMARGIN", new_y="NEXT"
        )

        detail = str(indicator.get("detail", "")).strip()
        if detail:
            pdf.set_x(48)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*_MUTED)
            pdf.multi_cell(150, 4.4, _ascii(detail), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(0.8)

    if len(indicators) > 14:
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(*_MUTED)
        pdf.multi_cell(
            186,
            5,
            _ascii(f"+ {len(indicators) - 14} further indicator(s) omitted for brevity."),
            new_x="LMARGIN",
            new_y="NEXT",
        )
    pdf.set_text_color(*_INK)


def _callout(pdf: "_ReportPDF", title: str, body: str, colour: tuple[int, int, int]) -> None:
    if pdf.get_y() > 240:
        pdf.add_page()
    top = pdf.get_y()
    pdf.set_fill_color(250, 251, 252)
    pdf.set_draw_color(*_LINE)
    pdf.set_x(12)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*colour)
    pdf.multi_cell(186, 5.6, _ascii(title), new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*_INK)
    pdf.multi_cell(186, 5.2, _ascii(body) or "-", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.set_draw_color(*colour)
    pdf.set_line_width(0.8)
    pdf.line(12, top, 12, pdf.get_y())
    pdf.set_line_width(0.2)
    pdf.ln(2)


def _target_rows(scan: dict[str, Any]) -> list[tuple[str, str]]:
    scan_type = str(scan.get("scan_type", ""))
    if hasattr(scan.get("scan_type"), "value"):
        scan_type = scan["scan_type"].value

    rows: list[tuple[str, str]] = []
    if scan.get("url"):
        rows.append(("Analysed URL", str(scan["url"])))
    if scan.get("message"):
        text = str(scan["message"])
        rows.append(("Message Text", text[:1200] + ("..." if len(text) > 1200 else "")))
    if scan.get("filename"):
        rows.append(("File Name", str(scan["filename"])))
        rows.append(
            (
                "File Details",
                f"{str(scan.get('file_type', '')).upper()} - "
                f"{round(int(scan.get('file_size') or 0) / 1024, 1)} KB",
            )
        )
        metadata = scan.get("document_metadata") or {}
        if metadata.get("sha256"):
            rows.append(("SHA-256", str(metadata["sha256"])))
    if scan.get("detected_categories"):
        rows.append(("Detected Categories", ", ".join(scan["detected_categories"])))
    if scan.get("suspicious_phrases"):
        rows.append(
            ("Suspicious Phrases", ", ".join(f'"{p}"' for p in scan["suspicious_phrases"][:8]))
        )
    if not rows:
        rows.append(("Target", str(scan.get("target_label", "-")) or f"{scan_type} scan"))
    return rows


def _technical_rows(scan: dict[str, Any]) -> list[tuple[str, str]]:
    details = scan.get("analysis_details") or {}
    rows: list[tuple[str, str]] = [("Engine", str(details.get("engine", "-")))]
    if details.get("prediction_source"):
        rows.append(("Prediction Source", str(details["prediction_source"]).replace("_", " ")))
    if details.get("heuristic_score") is not None:
        rows.append(("Heuristic Score", f"{float(details['heuristic_score']):.2f} / 100"))
    if details.get("model_probability") is not None:
        rows.append(("Model Probability", f"{float(details['model_probability']):.4f}"))
    model_meta = details.get("model_metadata") or {}
    if model_meta.get("algorithm"):
        rows.append(("Model", str(model_meta["algorithm"])))
    if model_meta.get("holdout_accuracy") is not None:
        rows.append(("Model Holdout Accuracy", f"{float(model_meta['holdout_accuracy']):.3f}"))
    if details.get("evidence_sources"):
        rows.append(("Evidence Sources", ", ".join(details["evidence_sources"])))
    capabilities = details.get("capabilities") or {}
    if capabilities:
        rows.append(
            (
                "OCR",
                "Available (Tesseract " + str(capabilities.get("tesseract_version") or "?") + ")"
                if capabilities.get("tesseract_ocr")
                else "Not installed - fallback analysis used",
            )
        )
    features = details.get("features") or {}
    if features:
        rows.append(
            (
                "URL Features",
                f"length={features.get('url_length')}, subdomains={features.get('num_subdomains')}, "
                f"digits={features.get('num_digits')}, entropy={features.get('entropy')}, "
                f"https={features.get('has_https')}",
            )
        )
    stats = details.get("text_statistics") or {}
    if stats:
        rows.append(
            (
                "Text Statistics",
                f"words={stats.get('word_count')}, uppercase={stats.get('uppercase_ratio')}, "
                f"exclamations={stats.get('exclamation_count')}",
            )
        )
    rows.append(("Indicators Triggered", str(details.get("indicator_count", len(scan.get("indicators", []))))))
    return rows


def generate_pdf_report(scan: dict[str, Any]) -> bytes:
    """Render a branded PDF report. Raises RuntimeError if fpdf2 is missing."""
    if not FPDF_AVAILABLE:
        raise RuntimeError("PDF generation requires fpdf2.")

    scan_type = scan.get("scan_type")
    scan_type_label = scan_type.value if hasattr(scan_type, "value") else str(scan_type)
    level = str(
        scan.get("risk_level").value
        if hasattr(scan.get("risk_level"), "value")
        else scan.get("risk_level", "LOW")
    )

    pdf = _ReportPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(12, 32, 12)
    pdf.set_title(f"{BRAND} Report - Scan #{scan.get('scan_id')}")
    pdf.set_author(BRAND)
    pdf.alias_nb_pages()
    pdf.add_page()

    _section(pdf, "Scan Information")
    _key_value_rows(
        pdf,
        [
            ("Report ID", f"FS-{int(scan.get('scan_id', 0)):06d}"),
            ("Scan Type", f"{scan_type_label} analysis"),
            ("Scan Date", _format_timestamp(scan.get("created_at"))),
            ("Status", str(getattr(scan.get("status"), "value", scan.get("status", "-")))),
            (
                "Analyst",
                f"{(scan.get('user') or {}).get('name', 'FraudShield user')} "
                f"({(scan.get('user') or {}).get('email', '-')})"
                if scan.get("user")
                else "FraudShield user",
            ),
            ("Report Generated", _format_timestamp(datetime.now(UTC))),
        ],
    )

    _section(pdf, "Risk Assessment")
    _risk_banner(
        pdf,
        float(scan.get("risk_score", 0) or 0),
        level,
        str(scan.get("prediction", "-")),
    )
    confidence = float(scan.get("confidence", 0) or 0)
    _key_value_rows(pdf, [("Engine Confidence", f"{confidence * 100:.1f}%")])

    _section(pdf, "Analysed Target")
    _key_value_rows(pdf, _target_rows(scan))

    _section(pdf, "Detected Indicators")
    _indicator_table(pdf, list(scan.get("indicators") or []))

    _section(pdf, "AI Explanation")
    _paragraph(pdf, str(scan.get("explanation", "")))

    _section(pdf, "Recommendation")
    _callout(
        pdf,
        "Recommended Action",
        str(scan.get("recommendation", "")),
        _LEVEL_COLOURS.get(level.upper(), _MUTED),
    )

    if scan.get("extracted_text"):
        _section(pdf, "Extracted Text (Excerpt)")
        excerpt = str(scan["extracted_text"])[:1500]
        pdf.set_font("Courier", "", 7.5)
        pdf.set_text_color(*_MUTED)
        pdf.multi_cell(186, 4, _ascii(excerpt), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*_INK)

    _section(pdf, "Technical Analysis Details")
    _key_value_rows(pdf, _technical_rows(scan))

    _section(pdf, "Disclaimer")
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*_MUTED)
    pdf.multi_cell(
        186,
        4.4,
        _ascii(scan.get("disclaimer") or DISCLAIMER),
        new_x="LMARGIN",
        new_y="NEXT",
    )

    output = pdf.output()
    return bytes(output) if not isinstance(output, bytes) else output


# --- HTML fallback ------------------------------------------------------------

_HTML_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>{brand} Report — Scan #{scan_id}</title>
<style>
  :root {{ --ink:#111827; --muted:#64748b; --line:#e2e8f0; --accent:{accent}; }}
  * {{ box-sizing:border-box; }}
  body {{ font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
         color:var(--ink); margin:0; padding:32px; background:#f8fafc; }}
  .sheet {{ max-width:840px; margin:0 auto; background:#fff; padding:0 0 40px;
            border-radius:12px; box-shadow:0 1px 3px rgba(0,0,0,.08); overflow:hidden; }}
  header {{ background:#111827; color:#fff; padding:22px 32px; }}
  header h1 {{ margin:0; font-size:20px; letter-spacing:-.02em; }}
  header p {{ margin:4px 0 0; font-size:12px; color:#94a3b8; }}
  main {{ padding:28px 32px 0; }}
  h2 {{ font-size:12px; text-transform:uppercase; letter-spacing:.08em;
        border-bottom:2px solid var(--accent); display:inline-block;
        padding-bottom:4px; margin:28px 0 12px; }}
  table {{ width:100%; border-collapse:collapse; font-size:13px; }}
  th,td {{ text-align:left; padding:7px 8px; border-bottom:1px solid var(--line);
           vertical-align:top; }}
  th {{ width:170px; color:var(--muted); font-weight:600; }}
  .banner {{ display:flex; gap:24px; align-items:center; background:#f8fafc;
             border:1px solid var(--line); border-left:4px solid var(--accent);
             padding:18px 22px; border-radius:8px; }}
  .score {{ font-size:40px; font-weight:700; color:var(--accent); line-height:1; }}
  .meter {{ height:8px; background:#e2e8f0; border-radius:99px; overflow:hidden;
            width:220px; margin-top:8px; }}
  .meter span {{ display:block; height:100%; width:{score_pct}%; background:var(--accent); }}
  .sev {{ font-size:10px; font-weight:700; padding:2px 7px; border-radius:99px;
          background:#f1f5f9; color:var(--muted); white-space:nowrap; }}
  .callout {{ background:#f8fafc; border-left:4px solid var(--accent);
              padding:14px 18px; border-radius:6px; font-size:13px; }}
  pre {{ background:#f8fafc; border:1px solid var(--line); padding:12px;
         border-radius:6px; font-size:11px; white-space:pre-wrap; }}
  footer {{ margin-top:32px; padding:16px 32px 0; border-top:1px solid var(--line);
            font-size:11px; color:var(--muted); font-style:italic; }}
  @media print {{ body {{ background:#fff; padding:0; }}
                  .sheet {{ box-shadow:none; border-radius:0; }} }}
</style></head><body>
<div class="sheet">
  <header><h1>{brand}</h1><p>{tagline} &middot; Fraud Analysis Report</p></header>
  <main>
    <h2>Scan Information</h2>
    <table>{info_rows}</table>
    <h2>Risk Assessment</h2>
    <div class="banner">
      <div><div class="score">{score:.0f}</div>
        <div style="font-size:11px;color:var(--muted)">/ 100 RISK SCORE</div></div>
      <div><strong style="color:var(--accent);font-size:15px">{level} RISK</strong>
        <div style="font-size:13px">Classification: {prediction}</div>
        <div class="meter"><span></span></div></div>
    </div>
    <h2>Analysed Target</h2>
    <table>{target_rows}</table>
    <h2>Detected Indicators</h2>
    <table>{indicator_rows}</table>
    <h2>AI Explanation</h2>
    <p style="font-size:13px;line-height:1.6">{explanation}</p>
    <h2>Recommendation</h2>
    <div class="callout">{recommendation}</div>
    {extracted_block}
    <h2>Technical Analysis Details</h2>
    <table>{technical_rows}</table>
  </main>
  <footer>{disclaimer}</footer>
</div>
<script>window.addEventListener("load", function () {{ setTimeout(window.print, 350); }});</script>
</body></html>
"""


def generate_html_report(scan: dict[str, Any]) -> str:
    """Print-friendly HTML report — the fallback when fpdf2 is unavailable."""
    level = str(
        scan.get("risk_level").value
        if hasattr(scan.get("risk_level"), "value")
        else scan.get("risk_level", "LOW")
    ).upper()
    colour = "#%02x%02x%02x" % _LEVEL_COLOURS.get(level, _ACCENT)
    score = float(scan.get("risk_score", 0) or 0)
    scan_type = scan.get("scan_type")
    scan_type_label = scan_type.value if hasattr(scan_type, "value") else str(scan_type)

    def rows(pairs: list[tuple[str, str]]) -> str:
        return "".join(
            f"<tr><th>{html.escape(label)}</th><td>{html.escape(str(value) or '-')}</td></tr>"
            for label, value in pairs
        )

    indicators = list(scan.get("indicators") or [])
    if indicators:
        indicator_rows = "".join(
            "<tr><td><span class='sev'>"
            f"{html.escape(_SEVERITY_LABEL.get(str(i.get('severity', 'low')).lower(), 'LOW'))}"
            "</span></td>"
            f"<td><strong>{html.escape(str(i.get('label', '-')))}</strong><br>"
            f"<span style='color:var(--muted);font-size:12px'>"
            f"{html.escape(str(i.get('detail', '')))}</span></td></tr>"
            for i in indicators
        )
    else:
        indicator_rows = (
            "<tr><td colspan='2'>No suspicious indicators were detected for this scan.</td></tr>"
        )

    extracted_block = ""
    if scan.get("extracted_text"):
        excerpt = html.escape(str(scan["extracted_text"])[:2000])
        extracted_block = f"<h2>Extracted Text (Excerpt)</h2><pre>{excerpt}</pre>"

    return _HTML_TEMPLATE.format(
        brand=BRAND,
        tagline=TAGLINE,
        accent=colour,
        scan_id=scan.get("scan_id"),
        score=score,
        score_pct=min(100.0, max(0.0, score)),
        level=html.escape(level),
        prediction=html.escape(str(scan.get("prediction", "-"))),
        info_rows=rows(
            [
                ("Report ID", f"FS-{int(scan.get('scan_id', 0)):06d}"),
                ("Scan Type", f"{scan_type_label} analysis"),
                ("Scan Date", _format_timestamp(scan.get("created_at"))),
                ("Status", str(getattr(scan.get("status"), "value", scan.get("status", "-")))),
                ("Engine Confidence", f"{float(scan.get('confidence', 0) or 0) * 100:.1f}%"),
                ("Report Generated", _format_timestamp(datetime.now(UTC))),
            ]
        ),
        target_rows=rows(_target_rows(scan)),
        indicator_rows=indicator_rows,
        explanation=html.escape(str(scan.get("explanation", ""))),
        recommendation=html.escape(str(scan.get("recommendation", ""))),
        extracted_block=extracted_block,
        technical_rows=rows(_technical_rows(scan)),
        disclaimer=html.escape(str(scan.get("disclaimer") or DISCLAIMER)),
    )


def build_report(scan: dict[str, Any], fmt: str = "pdf") -> tuple[bytes, str, str]:
    """Build a report.

    Returns ``(content, media_type, filename)``. Falls back to HTML if the PDF
    backend is unavailable or errors, so the download always succeeds.
    """
    stem = f"FraudShield-Report-FS-{int(scan.get('scan_id', 0)):06d}"
    if fmt.lower() == "pdf" and FPDF_AVAILABLE:
        try:
            return generate_pdf_report(scan), "application/pdf", f"{stem}.pdf"
        except Exception as exc:  # pragma: no cover
            logger.warning("PDF generation failed (%s); falling back to HTML.", exc)

    html_body = generate_html_report(scan)
    return html_body.encode("utf-8"), "text/html; charset=utf-8", f"{stem}.html"


def report_stream(content: bytes) -> io.BytesIO:
    return io.BytesIO(content)
